PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ex: <http://example.org/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>

###################################
# This query is used to test GeoSPARQL geometry; it always returns the same geometries. 
# 1) a point   (CRS: WGS 84)
# 2) a line    (CRS: WGS 84)
# 3) a polygon (CRS: WGS 84)
# 4) a point   (CRS: EPSG 28992)
# 5) a point   (CRS: -)
# 6) a point   (CRS: ESPG 28992, via variable)
#
# For WGS 84, the identification is as follows:
# IRI <http://www.opengis.net/def/crs/OGC/1.3/CRS84> (used in GeoSPARQL) and
# IRI <https://www.opengis.net/def/crs/EPSG/9.9.1/4326> and
# URN <urn:ogc:def:crs:OGC::CRS84>.
#
# Note that it is not uncommon for datasets to leave the CRS unspecified and,
# although not according to the GeoSPARQL standard, assume a certain CRS (e.g., 
# EPSG 28992, or Rijksdriehoek, in Dutch datasets, with 
# IRI <https://www.opengis.net/def/crs/EPSG/9.9.1/28992> and 
# URN <urn:ogc:def:crs:EPSG::28992>).
###################################


SELECT ?entry_iri ?entry_text ?location_wkt ?location_crs ?location_text ?location_color
WHERE {
    {
      #1) a Point w/ WGS 84 as CRS (the CRS assumed/required by many map visualizations)
      BIND (ex:asset1 AS ?entry_iri) .
      BIND (ex:asset1_geo AS ?entityInterior) .
      BIND ("<http://www.opengis.net/def/crs/OGC/1.3/CRS84> Point (-83.5 34.2)"^^geo:wktLiteral AS ?location_wkt) .
      BIND ("#aa0000" AS ?location_color) . # see https://docs.mapbox.com/mapbox-gl-js/style-spec/types/#color
      BIND (STRDT(CONCAT("<h1>Asset 1</h1>IRI: ", STR(?entry_iri)), rdf:HTML) AS ?location_text) .
    }
    UNION
    {
      #2) a LineString w/ WGS 84 as CRS (the CRS assumed/required by many map visualizations)
      BIND (ex:asset2 AS ?entry_iri) .
      BIND (ex:asset2_geo AS ?entityInterior) .
      BIND ("<http://www.opengis.net/def/crs/OGC/1.3/CRS84> LineString (-83.4 34.0, -83.3 34.3)"^^geo:wktLiteral AS ?location_wkt) .
      BIND ("#00aa00" AS ?location_color) . # see https://docs.mapbox.com/mapbox-gl-js/style-spec/types/#color
      BIND (STRDT(CONCAT("<h1>Asset 2</h1>IRI: ", STR(?entry_iri)), rdf:HTML) AS ?location_text) .
    }
    UNION
    {
      #3) a Polygon w/ WGS 84 as CRS (the CRS assumed/required by many map visualizations)
      BIND (ex:asset3 AS ?entry_iri) .
      BIND (ex:asset3_geo AS ?entityInterior) .
      BIND ("<http://www.opengis.net/def/crs/OGC/1.3/CRS84> Polygon ((-83.6 34.1, -83.2 34.1, -83.2 34.5, -83.6 34.5, -83.6 34.1))"^^geo:wktLiteral AS ?location_wkt) .
      BIND (STRDT(CONCAT("<h1>Asset 3</h1>IRI: ", STR(?entry_iri)), rdf:HTML) AS ?location_text) .
    }
    UNION
    {
      #4) a Point w/ another CRS (used in the Netherlands)
      BIND (ex:asset4 AS ?entry_iri) .
      BIND (ex:asset4_geo AS ?entityInterior) .
      BIND ("<https://www.opengis.net/def/crs/EPSG/9.9.1/28992> Point (139844 443660)"^^geo:wktLiteral AS ?location_wkt) .
      BIND ("#aa00aa" AS ?location_color) . # see https://docs.mapbox.com/mapbox-gl-js/style-spec/types/#color
      BIND (STRDT(CONCAT("<h1>Asset 4</h1>IRI: ", STR(?entry_iri)), rdf:HTML) AS ?location_text) .
    }
    UNION
    {
      #5) a Point w/ an implicit CRS (by definition this is WGS 84, but many datasets use a custom CRS as default instead)
      BIND (ex:asset5 AS ?entry_iri) .
      BIND (ex:asset5_geo AS ?entityInterior) .
      BIND ("Point (-83.9 34.0)"^^geo:wktLiteral AS ?location_wkt) .
      BIND ("#00aaaa" AS ?location_color) . # see https://docs.mapbox.com/mapbox-gl-js/style-spec/types/#color
      BIND (STRDT(CONCAT("<h1>Asset 5</h1>IRI: ", STR(?entry_iri)), rdf:HTML) AS ?location_text) .
    }
    UNION
    {
      #6) a Point w/ an implicit CRS but indicated through a separate CRS variable
      BIND (ex:asset6 AS ?entry_iri) .
      BIND (ex:asset6_geo AS ?entityInterior) .
      BIND ("Point (155000 463000)"^^geo:wktLiteral AS ?location_wkt) .
      BIND (STRDT(CONCAT("<h1>Asset 6</h1>IRI: ", STR(?entry_iri)), rdf:HTML) AS ?location_text) .
      BIND ("#aaaa00" AS ?location_color) . # see https://docs.mapbox.com/mapbox-gl-js/style-spec/types/#color
      BIND (<https://www.opengis.net/def/crs/EPSG/9.9.1/28992> AS ?location_crs) .
    }
}